title: Services                                                           
description:
  Timothy G. Mings, MAI, has been appraising properties in California since 1987. Tim focuses on all types of income producing properties including but not limited to industrial, office, retail, land and residential income properties. Clients served include banks, commercial lenders, mortgage bankers, government agencies, private estates. Services offered include self-contained, summary, and restricted reports catered to client needs for intended purposes such as sale, lending, new construction, asset monitoring, estate planning, and partial interest valuation.

  Empire VAS conducts business in accordance with the Code of Professional Ethics of the Appraisal Institute and the Uniform Standards of Professional Appraisal Practice (USPAP). Empire VAS focuses on primary research from the local market. We have an extensive network of local property owner, broker, lender, and developer contacts that allows for real time property information pertinent to each valuation. We take pride in providing accurate, honest, and objective results in a timely manner. We cater our services to the specific needs of the client based on current market conditions.

section:
Inland Empire (Riverside & San Bernardino Counties), Pomona and San Gabriel Valleys in eastern Los Angeles County.

Secondary Market Areas:

High Desert and Palm Springs Areas, Los Angeles County, Orange County, San Diego County, Ventura County, Kern County, Imperial County, Santa Barbara County, San Luis Obispo County, Tulare County, Kings County, Fresno County, Inyo County

Primary Practice:

Commercial, Industrial, Office, Retail, Land, Mixed-Use, Multi-Family Residential and Special-Use Properties in Southern California

Business Services:

Acquisition, Disposition - Appraisal • Appraisal Review • Retrospective Valuation • Real Estate Tax Valuation and Consulting • Probate and Estates • Consulting • Partial Interest Valuation • Litigation / Litigation Support • Data and Information Analysis • Demand Analysis • Demographic Analysis • Consultation Market Analysis • Mortgage Lending Consulting • Non-cash Charitable Contributions • Portfolio Valuation and Analysis • Site Location Analysis and Consulting • Valuation and Consultation for Financial Reporting

Property Types:

Industrial: Warehouse/Distribution • Manufacturing • Business Park • Food Processing • Cold Storage • Research and Development Lab / Hi-Tech / Bioengineering • Truck Terminal / Hub / Transit Facility • Self Storage • Contractor Yard • Lumber Yard • Gravel Pit

Office: Office • Medical Office • Surgery Center • Hospital • Call Center • Data Center

Retail/Commercial: Shopping Centers (Local, Strip, Neighborhood, Community, Power, Etc.) • Net Leased Investment • Branch Bank / Financial Building • Condominium • Convenience Store / Service station • Day Care • Movie Theatre • Parking Facility (Lot or Garage) • Restaurant / Bar / Night Club • Retail (Single Tenant or Free Standing) • School• Automobile Dealership • Banquet / Reception Hall • Church

Residential: Apartment • Senior Apartment • Low Income and/or Affordable Housing • Mixed Use (Residential / Commercial) • Multi-family (5+ units)

Land: Industrial • Retail • Office • Commercial • Multifamily • Mixed Use • Acreage (Non-Residential) • Urban/Suburban

Public: Community Center / Recreation Center • Public Service / Municipal Service Building • Religious Facility

Other: Partial Interest Valuation • Right of Way • Youth Rehabilitation Facilities • Ground Lease Valuation • Marketing Packages